### ISSUE TITLE
Outdated Molang

### ISSUE THREAD

**Issue by SmokeyStack** [Bedrock-OSS/bedrock-wiki-vite#930]
https://wiki.bedrock.dev/entities/detecting-other-entities

Page above used a removed molang query, we should do a sweep of the wiki to check for outdated queries.

**Comment by QuazChick** [comment]
https://wiki.bedrock.dev/documentation/advanced-molang also uses `q.get_nearby_entities`, all information about entity iterables can probably be removed.

https://wiki.bedrock.dev/concepts/molang uses the deprecated `q.get_equipped_item_name` (should be replaced with a query that still demonstrates usage of `==`).

https://wiki.bedrock.dev/loot/recipes uses `q.get_actor_info_id` which isn't deprecated, but since spawn eggs now have separate IDs, it may not be needed.

**Comment by QuazChick** [comment]
Resolved 6a3c141
